service: serverless
app: serverless
org: gabrielfior
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: outlook
  #region: eu-central-1

functions:
  hello:
    handler: handler.hello
    #events:
    #  - schedule: rate(1 minute)

plugins:
  - serverless-esbuild
